language: bash
services: docker

env:
  - VERSION=2.12.3 VARIANT=vanilla
  - VERSION=2.12.3 VARIANT=gcp
  - VERSION=2.12.0 VARIANT=vanilla
  - VERSION=2.12.0 VARIANT=gcp
  - VERSION=2.11.0 VARIANT=vanilla
  - VERSION=2.11.0 VARIANT=gcp
  - VERSION=2.10.0 VARIANT=vanilla
  - VERSION=2.10.0 VARIANT=gcp
  - VERSION=2.9.1 VARIANT=vanilla
  - VERSION=2.9.1 VARIANT=gcp

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="cousine${slash}helm-kubectl-secrets:${VERSION}-${VARIANT//$slash/-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
    )

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $image
